export interface ProjectSpec {
    id: string;
    projectNo: string;
    code: string;
    tonnage?: number;
    client: string;
    buildingType: string;
    category: 'Warehouse' | 'Factory & Process Plant' | 'Infrastructure & Multistory';
    height?: string;
    areaSqm?: number;
    areaSqft?: number;
    kgPerSqft?: number;
    location: string;
    status: string;
    image: string;
}

export const projectsData: ProjectSpec[] = [
    {
        id: '1',
        projectNo: '001',
        code: 'KAM B3',
        tonnage: 450.336,
        client: 'B3 Moksh',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 15215.7,
        areaSqft: 163720.8,
        kgPerSqft: 2.75,
        location: 'Moksh Sawad Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/1-Moksha-sawad-Naka-bhiwandi.jpg'
    },
    {
        id: '2',
        projectNo: '002',
        code: 'KAM B2',
        tonnage: 379.102,
        client: 'B2 Moksh',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '11.25',
        areaSqm: 12650.6,
        areaSqft: 136120.2,
        kgPerSqft: 2.79,
        location: 'Moksh Sawad Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/B2-Moksh-Warehouse.jpeg'
    },
    {
        id: '3',
        projectNo: '003',
        code: 'KAM B5',
        tonnage: 1420,
        client: 'B5 Paramount',
        buildingType: 'Torrent Pharma Process Building',
        category: 'Factory & Process Plant',
        height: '14.369',
        areaSqm: 30925.6,
        areaSqft: 332759.0,
        kgPerSqft: 4.27,
        location: 'Paramount Sawad Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/B5-Paramount-Torrent-pharma.jpg'
    },
    {
        id: '4',
        projectNo: '004',
        code: 'GOL G',
        tonnage: 518,
        client: 'RK Logi G',
        buildingType: 'DHL Warehouse',
        category: 'Warehouse',
        height: '11.372',
        areaSqm: 18013.5,
        areaSqft: 193825.4,
        kgPerSqft: 2.67,
        location: 'RK Logi Yewai Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Logi-G-DHL-Warehouse.jpeg'
    },
    {
        id: '7',
        projectNo: '007',
        code: 'GOL B',
        tonnage: 135,
        client: 'RK Logi B',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 4202.0,
        areaSqft: 45213.5,
        kgPerSqft: 2.99,
        location: 'RK Logi Yewai Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Logi-B-Warehouse.jpeg'
    },
    {
        id: '8',
        projectNo: '008',
        code: 'GOL F',
        tonnage: 232,
        client: 'RK Logi F',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 7209.9,
        areaSqft: 77578.5,
        kgPerSqft: 2.99,
        location: 'RK Logi Yewai Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Logi-F-Warehouse.jpeg'
    },
    {
        id: '9',
        projectNo: '009',
        code: 'GOL D3',
        tonnage: 900.53,
        client: 'Global D',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 27870.0,
        areaSqft: 299881.2,
        kgPerSqft: 3.00,
        location: 'Global Park 1, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-D-Warehouse.jpeg'
    },
    {
        id: '10',
        projectNo: '010',
        code: 'PAR N',
        tonnage: 65,
        client: 'Shree Krishna Farm',
        buildingType: 'Process Building',
        category: 'Factory & Process Plant',
        height: '17',
        areaSqm: 149.6,
        areaSqft: 1609.2,
        kgPerSqft: 40.39,
        location: 'Nichole, Wada',
        status: 'Handovered',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '11',
        projectNo: '011',
        code: 'GOL G',
        tonnage: 250,
        client: 'RK Global H',
        buildingType: 'Spoton Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 6934.5,
        areaSqft: 74615.2,
        kgPerSqft: 3.35,
        location: 'Global Park 1, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Global-G-Spoton-Warehouse.jpeg'
    },
    {
        id: '12',
        projectNo: '012',
        code: 'GOL D1',
        tonnage: undefined,
        client: 'RK Global D1',
        buildingType: 'Spoton Warehouse',
        category: 'Warehouse',
        height: '9',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Global Park 1, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Global-G-Spoton-Warehouse.jpeg'
    },
    {
        id: '13',
        projectNo: '013',
        code: 'GOL A1',
        tonnage: undefined,
        client: 'RK Global A1',
        buildingType: 'DHL Warehouse',
        category: 'Warehouse',
        height: '10m - 13m',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Global Talwali, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Logi-G-DHL-Warehouse.jpeg'
    },
    {
        id: '14',
        projectNo: '014',
        code: 'RICH D9',
        tonnage: undefined,
        client: 'Rich Land Developer',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '8',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Vadpe, Bhiwandi',
        status: 'Handovered',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '17',
        projectNo: '017',
        code: 'GOL2 B2',
        tonnage: 263.39,
        client: 'Global 2',
        buildingType: 'Siemens Warehouse',
        category: 'Warehouse',
        height: '9',
        areaSqm: 8749.0,
        areaSqft: 94139.5,
        kgPerSqft: 2.80,
        location: 'Janwal, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-2-Siemens-warehouse.jpeg'
    },
    {
        id: '18',
        projectNo: '018',
        code: 'RK H',
        tonnage: 358.42,
        client: 'RK Global H',
        buildingType: 'Gati Warehouse',
        category: 'Warehouse',
        height: '9',
        areaSqm: 10769.9,
        areaSqft: 115883.9,
        kgPerSqft: 3.09,
        location: 'RK Logi Yewai Naka, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/RK-Global-H-Gati-Warehouse.jpeg'
    },
    {
        id: '20',
        projectNo: '020',
        code: 'GOL2 S200',
        tonnage: 787.75,
        client: 'Sumit Mhatre Logistics',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Bhinar, Bhiwandi',
        status: 'Handovered',
        image: 'https://khushipebinfrastructure.com/wp-content/uploads/2026/07/3-3-scaled.jpg'
    },
    {
        id: '21',
        projectNo: '021',
        code: 'GOL2 A3',
        tonnage: 817.82,
        client: 'Global Logistics',
        buildingType: 'Piplas Bhiwandi',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Piplas Bhumi Logi World',
        status: 'Erection',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-Logistics-Piplas-Bhiwandi.jpeg'
    },
    {
        id: '22',
        projectNo: '022',
        code: 'GOL2 S300',
        tonnage: 774.48,
        client: 'Sumit Mhatre Logistics',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Bhinar, Bhiwandi',
        status: 'Anchor Bolting',
        image: 'https://khushipebinfrastructure.com/wp-content/uploads/2026/07/3-3-scaled.jpg'
    },
    {
        id: '23',
        projectNo: '023',
        code: 'GOL I',
        tonnage: 603.14,
        client: 'RK Logi I',
        buildingType: 'Hellmann Worldwide Logistics',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'RK Logi Yewai Naka',
        status: 'Handovered',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '25',
        projectNo: '025',
        code: 'MGL PL',
        tonnage: 104.5,
        client: 'Shri Krishna Pharma',
        buildingType: 'Foils (I) Factory',
        category: 'Factory & Process Plant',
        height: '9m - 12.8m',
        areaSqm: 2554.8,
        areaSqft: 27500.2,
        kgPerSqft: 3.80,
        location: 'Pali Phata, Wada',
        status: 'Erection',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '26',
        projectNo: '026',
        code: 'SKL B500',
        tonnage: 1317,
        client: 'Shree Krishna',
        buildingType: 'DHL B500 Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 41184.0,
        areaSqft: 443304.6,
        kgPerSqft: 2.97,
        location: 'Dhamangaon, Bhiwandi',
        status: 'Sheeting',
        image: 'https://khushipebinfrastructure.com/wp-content/uploads/2026/07/DJI_0519-scaled.webp'
    },
    {
        id: '29',
        projectNo: '029',
        code: 'BM B3',
        tonnage: 686.64,
        client: 'Global Logistics',
        buildingType: 'Piplas Bhiwandi',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Piplas, Bhiwandi',
        status: 'Erection',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-Logistics-Piplas-Bhiwandi.jpeg'
    },
    {
        id: '30',
        projectNo: '030',
        code: 'GOL B',
        tonnage: 108.91,
        client: 'Global Reality',
        buildingType: 'Talvli Warehouse',
        category: 'Warehouse',
        height: '9',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Talwali, Bhiwandi',
        status: 'Handovered',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-D-Warehouse.jpeg'
    },
    {
        id: '31',
        projectNo: '031',
        code: 'KAM A3',
        tonnage: 440.53,
        client: 'Moksha Logistics',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Moksh Sawad Naka',
        status: 'Erection',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/1-Moksha-sawad-Naka-bhiwandi.jpg'
    },
    {
        id: '32',
        projectNo: '032',
        code: 'BM NL',
        tonnage: 308.92,
        client: 'Sumit Mhatre Logistics',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Nimbovali Bhinar',
        status: 'Anchor Bolting',
        image: 'https://khushipebinfrastructure.com/wp-content/uploads/2026/07/3-3-scaled.jpg'
    },
    {
        id: '33',
        projectNo: '033',
        code: 'KAM B3',
        tonnage: 350.51,
        client: 'B3 Paramount',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: undefined,
        areaSqft: undefined,
        kgPerSqft: undefined,
        location: 'Paramount, Bhiwandi',
        status: 'Anchor Bolting',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/1-Moksha-sawad-Naka-bhiwandi.jpg'
    },
    {
        id: '35',
        projectNo: '035',
        code: 'MINI FAB',
        tonnage: 219.395,
        client: 'Toros Engineering',
        buildingType: 'Factory',
        category: 'Factory & Process Plant',
        height: '10',
        areaSqm: 4215.4,
        areaSqft: 45374.7,
        kgPerSqft: 0.00,
        location: 'Abitghar, Wada',
        status: 'Handovered + Lean too in progress',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '38',
        projectNo: '038',
        code: 'S200 G3',
        tonnage: 829.825,
        client: 'LP (India) Logistics Pvt Ltd',
        buildingType: 'G+3 Warehouse',
        category: 'Warehouse',
        height: '9.41',
        areaSqm: 13935.0,
        areaSqft: 149996.3,
        kgPerSqft: 5.53,
        location: 'Bhiwandi',
        status: 'At Handover',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '39',
        projectNo: '039',
        code: 'GEN ST',
        tonnage: 214,
        client: 'General Polyfilms Pvt Ltd',
        buildingType: 'Factory',
        category: 'Factory & Process Plant',
        height: '8.8',
        areaSqm: 2347.3,
        areaSqft: 25265.9,
        kgPerSqft: 8.47,
        location: 'Navapur, Nandurbar',
        status: 'Anchor Bolting',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '42',
        projectNo: '042',
        code: 'ADB PC',
        tonnage: 92.225,
        client: 'Parshwa Cashew',
        buildingType: 'Factory',
        category: 'Factory & Process Plant',
        height: '8',
        areaSqm: 2531,
        areaSqft: 27241.9,
        kgPerSqft: 3.39,
        location: 'Ahmedabad, Gujarat',
        status: 'Handovered',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '43',
        projectNo: '043',
        code: 'BM A4',
        tonnage: 196,
        client: 'Global Logistics',
        buildingType: 'Piplas Bhiwandi',
        category: 'Warehouse',
        height: '11.143',
        areaSqm: 6140.2,
        areaSqft: 66093.3,
        kgPerSqft: 2.97,
        location: 'Piplas, Bhiwandi',
        status: 'Erection',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-Logistics-Piplas-Bhiwandi.jpeg'
    },
    {
        id: '44',
        projectNo: '044',
        code: 'SYN A3',
        tonnage: 208.363,
        client: 'Symphony Logistics',
        buildingType: 'EH12 Warehouse',
        category: 'Warehouse',
        height: undefined,
        areaSqm: 5904.3,
        areaSqft: 63553.9,
        kgPerSqft: 3.28,
        location: 'Sawad Naka, Bhiwandi',
        status: 'GA in Progress',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '46',
        projectNo: '046',
        code: 'VRN A1',
        tonnage: 110.22,
        client: 'Varun Patil',
        buildingType: 'Warehouse EH12',
        category: 'Warehouse',
        height: undefined,
        areaSqm: 2948.5,
        areaSqft: 31737.7,
        kgPerSqft: 3.47,
        location: 'Sawad Naka, Bhiwandi',
        status: 'Anchor Bolting',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '47',
        projectNo: '047',
        code: 'MIPL WD',
        tonnage: 462,
        client: 'Master India Pvt Ltd',
        buildingType: 'Aluminium Process Factory',
        category: 'Factory & Process Plant',
        height: '11',
        areaSqm: 5244.0,
        areaSqft: 56446.4,
        kgPerSqft: 8.18,
        location: 'Wada',
        status: 'Erection',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '49',
        projectNo: '049',
        code: 'BM B4',
        tonnage: 298.72,
        client: 'Global Logistics',
        buildingType: 'Piplas Bhiwandi EH12',
        category: 'Warehouse',
        height: undefined,
        areaSqm: 9403.5,
        areaSqft: 101219.3,
        kgPerSqft: 2.95,
        location: 'Piplas, Bhiwandi',
        status: 'Erection',
        image: 'https://www.steelwonders.in/wp-content/uploads/2025/12/Global-Logistics-Piplas-Bhiwandi.jpeg'
    },
    {
        id: '50',
        projectNo: '050',
        code: 'SKL B200',
        tonnage: 856.95,
        client: 'Sai Krishna Warehousing',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 24648.0,
        areaSqft: 265311.1,
        kgPerSqft: 3.23,
        location: 'Dhamangaon, Bhiwandi',
        status: 'GA in Progress',
        image: 'https://khushipebinfrastructure.com/wp-content/uploads/2026/07/DJI_0519-scaled.webp'
    },
    {
        id: '53',
        projectNo: '053',
        code: 'VPV A1',
        tonnage: 650,
        client: 'Varun Patil',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 19291.7,
        areaSqft: 207656.1,
        kgPerSqft: 3.13,
        location: 'Bhiwandi',
        status: 'Civil in Progress',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '54',
        projectNo: '054',
        code: 'KWN F',
        tonnage: 661,
        client: 'Kelween Logistics',
        buildingType: 'Warehouse',
        category: 'Warehouse',
        height: '12',
        areaSqm: 18932.5,
        areaSqft: 203789.4,
        kgPerSqft: 3.24,
        location: 'Sawad Naka, Bhiwandi',
        status: 'GA in Progress',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '55b',
        projectNo: '054b',
        code: 'TIPL WL',
        tonnage: 262,
        client: 'Trupti Infra (Birla Project)',
        buildingType: 'Birla Project G+10',
        category: 'Infrastructure & Multistory',
        height: '32',
        areaSqm: 480.0,
        areaSqft: 5166.7,
        kgPerSqft: 50.71,
        location: 'Worli, Mumbai',
        status: 'Anchor Bolting',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    },
    {
        id: '56',
        projectNo: '055',
        code: 'KYN E',
        tonnage: 140,
        client: 'Indian Railway',
        buildingType: 'Railway Station G+3 Extension',
        category: 'Infrastructure & Multistory',
        height: '11',
        areaSqm: 192.0,
        areaSqft: 2066.7,
        kgPerSqft: 67.74,
        location: 'Kalyan East',
        status: 'Anchor Bolting',
        image: 'https://res.cloudinary.com/dpctlwaam/image/upload/v1785704409/Steel_frame_structure_k0v326.webp'
    }
];
